### ISSUE TITLE
Link incorrecto a especificación de SPARQL

### ISSUE THREAD

**Issue by isidoravs** [IIC3432/Syllabus-2020-2#4]
En el [readme de Grafos](https://github.com/IIC3432/Syllabus-2020-2/blob/master/Grafos/readme.md) el link a la especificación de SPARQL lleva al endpoint de wikidata, por si lo podría cambiar para revisar ese material.
Muchas gracias!

**Comment by juanreutter** [comment]
Listo, gracias
